### ISSUE TITLE
Client Setup

### ISSUE THREAD

**Issue by bthnorhan** [vswarte/waygate-server#10]
Can you add client setup in readme?  How do I configure Elden ring to connect to this server?

**Comment by vswarte** [comment]
I'll get on the client docs soon :-)

In your case, you can either change the credentials in https://github.com/vswarte/waygate-client/blob/main/src/config.rs#L19-L30

or supply a `waygate.toml` in the `Game/` directory with contents like this:
```toml
host = "127.0.0.1"
port = 10901
verify_certificate = false
client_secret_key = "<replace with key>"
server_public_key = "<replace with key>"
```

please note that `verify_certificate` is largely untested and I recommend leaving it to `false` for now
